Repository gardener/gardener-extension-networking-cilium, pull requests merged in 2020-10, with the labels that each got.

#24 Update Cilium to version v1.8.4
  charts/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm

#26 Enhance extension's chart values
  .ci/pipeline_definitions
  Dockerfile
  charts/gardener-extension-networking-cilium/templates/deployment.yaml
  charts/gardener-extension-networking-cilium/templates/vpa.yaml
  charts/gardener-extension-networking-cilium/values.yaml
  example/controller-registration.yaml
Labels: area/documentation, area/robustness, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#27 Add docs link to README
  README.md
Labels: reviewed/lgtm, size/xs

#28 add priority class for extension pods
  charts/gardener-extension-networking-cilium/templates/_helpers.tpl
  charts/gardener-extension-networking-cilium/templates/deployment.yaml
  charts/gardener-extension-networking-cilium/templates/priorityclass.yaml
  example/controller-registration.yaml
Labels: area/high-availability, area/networking, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs
