Repository gardener/gardener-extension-networking-cilium, pull requests merged in 2020-09, with the labels that each got.

#18 Cleanup make test
  Makefile
Labels: kind/cleanup, needs/ok-to-test, priority/normal, reviewed/lgtm

#20 Add verify step to all jobs
  .ci/pipeline_definitions
Labels: needs/ok-to-test, reviewed/lgtm

#21 chmod +x for verify file
  .ci/verify
Labels: needs/ok-to-test

#14 Expose monitoring configuration for Cilium
  charts/images.yaml
  charts/internal/cilium-monitoring/Chart.yaml
  charts/internal/cilium-monitoring/charts/util-templates
  charts/internal/cilium-monitoring/cilium-agent-metrics-dashboard.json
  charts/internal/cilium-monitoring/cilium-operator-metrics-dashboard.json
  charts/internal/cilium-monitoring/hubble-metrics-dashboard.json
  charts/internal/cilium-monitoring/templates/_helpers.tpl
  charts/internal/cilium-monitoring/templates/cilium-monitoring-config.yaml
  charts/internal/cilium-monitoring/values.yaml
  charts/internal/cilium/charts/agent/templates/podsecuritypolicy.yaml
  charts/internal/cilium/charts/hubble-relay/templates/deployment.yaml
  charts/internal/cilium/charts/operator/templates/podsecuritypolicy.yaml
  charts/internal/cilium/charts/utils-templates
  charts/internal/cilium/values.yaml
  charts/utils-templates/Chart.yaml
  charts/utils-templates/README.md
  charts/utils-templates/templates/_versions.tpl
  pkg/charts/utils.go
  pkg/cilium/types.go
  pkg/controller/actuator.go
  pkg/controller/actuator_delete.go
  pkg/controller/actuator_reconcile.go
Labels: area/monitoring, area/networking, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#22 Update go version to 1.14
  Dockerfile
  go.mod
  hack/update-codegen.sh
  vendor/modules.txt
Labels: needs/ok-to-test, reviewed/lgtm

#23 Add end user documentation to cilium
  docs/usage-as-end-user.md
Labels: needs/ok-to-test, reviewed/lgtm
