Repository gardener/gardener-extension-networking-cilium, pull requests merged in 2020-11, with the labels that each got.

#30 Vendor to gardener v1.12.6
  .ci/pipeline_definitions
  Dockerfile
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/pkg/apis/core/types_shoot.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/defaults.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/generated.proto
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/helper/shootstate_list.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/types_shoot.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/constants/types_constants.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/defaults.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/generated.proto
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/helper/errors.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/helper/helper.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/types_shoot.go
  vendor/github.com/gardener/gardener/pkg/controllerutils/miscellaneous.go
  vendor/github.com/gardener/gardener/pkg/operation/common/utils.go
  vendor/github.com/gardener/gardener/pkg/utils/flow/taskfn.go
  vendor/github.com/gardener/gardener/pkg/utils/secrets/certificates.go
  vendor/modules.txt
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#31 Update cilium to v1.8.5 and update missing clusterrole permissions.
  charts/images.yaml
  charts/internal/cilium/charts/agent/templates/clusterrole.yaml
  charts/internal/cilium/charts/config/templates/configmap.yaml
  charts/internal/cilium/charts/operator/templates/clusterrole.yaml
  charts/internal/cilium/charts/operator/templates/deployment.yaml
  charts/internal/cilium/values.yaml
Labels: area/networking, kind/bug, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/s

#33 Honor --max-concurrent-reconciles flag
  Makefile
  cmd/gardener-extension-networking-cilium/app/app.go
Labels: area/quality, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#34 Disable cache for Secrets and ConfigMaps
  Makefile
  cmd/gardener-extension-networking-cilium/app/app.go
Labels: area/cost, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs
