Repository gardener/gardener-extension-networking-cilium, pull requests merged in 2021-06, with the labels that each got.

#50 Update README.md
  README.md
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#52 Unify container image tag in Makefile
  Makefile
Labels: needs/ok-to-test

#53 Update cilium to v1.10.1
  charts/images.yaml
  charts/internal/cilium/charts/agent/templates/clusterrole.yaml
  charts/internal/cilium/charts/agent/templates/daemonset.yaml
  charts/internal/cilium/charts/config/templates/configmap.yaml
  charts/internal/cilium/charts/hubble-relay/templates/deployment.yaml
  charts/internal/cilium/charts/hubble-ui/templates/configmap.yaml
  charts/internal/cilium/charts/operator/templates/clusterrole.yaml
  charts/internal/cilium/charts/operator/templates/deployment.yaml
  charts/internal/cilium/values.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/m

#55 Add a link to the cherry-pick-pr script from gardener
  Makefile
  hack/cherry-pick-pull.sh
Labels: area/dev-productivity, area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs
