Repository gardener/gardener-extension-networking-cilium, pull requests merged in 2021-07, with the labels that each got.

#57 Make leader election resource lock configurable and default to leases
  charts/gardener-extension-networking-cilium/templates/deployment.yaml
  charts/gardener-extension-networking-cilium/values.yaml
  cmd/gardener-extension-networking-cilium/app/app.go
  example/controller-registration.yaml
Labels: kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#58 drop support for k8s < v.1.15.0
  charts/gardener-extension-networking-cilium/templates/_helpers.tpl
  charts/utils-templates/templates/_versions.tpl
  example/controller-registration.yaml
Labels: area/networking, kind/cleanup, needs/ok-to-test, reviewed/lgtm, size/s

#56 Added kube-proxy clean up as init container in case cilium performs the service routing
  charts/images.yaml
  charts/internal/cilium/charts/agent/templates/daemonset.yaml
  charts/internal/cilium/charts/agent/values.yaml
  charts/internal/cilium/values.yaml
  pkg/charts/utils.go
  pkg/charts/values.go
  pkg/cilium/types.go
  pkg/controller/actuator_reconcile.go
  pkg/imagevector/image_finders.go
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/s

#61 Use flag from shoot spec instead of network extension to decide whether kube proxy is enabled/disabled.
  hack/api-reference/cilium.md
  pkg/apis/cilium/types_network.go
  pkg/apis/cilium/v1alpha1/types_network.go
  pkg/apis/cilium/v1alpha1/zz_generated.conversion.go
  pkg/apis/cilium/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/cilium/zz_generated.deepcopy.go
  pkg/charts/utils.go
Labels: area/networking, kind/api-change, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/s

#62 update cilium to v1.10.3
  charts/images.yaml
  charts/internal/cilium/charts/agent/templates/daemonset.yaml
  charts/internal/cilium/charts/config/templates/configmap.yaml
  charts/internal/cilium/values.yaml
Labels: area/networking, needs/ok-to-test, reviewed/lgtm, size/s
