Repository gardener/gardener-extension-networking-cilium, pull requests merged in 2022-12, with the labels that each got.

#143 Add missing annotations for seccomp profiles to pod security policies.
  charts/internal/cilium/charts/hubble-relay/templates/podsecuritypolicy.yaml
Labels: area/networking, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#144 Use resources.gardener.cloud/delete-on-invalid-update annotation for hubble generate certificate job.
  charts/internal/cilium/charts/hubble-relay/templates/job.yaml
Labels: area/networking, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#145 Drop support for kubernetes < 1.20 for cilium extension
  charts/internal/cilium/charts/agent/templates/daemonset.yaml
  charts/internal/cilium/charts/hubble-relay/templates/cronjob.yaml
  charts/internal/cilium/charts/hubble-relay/templates/deployment.yaml
  charts/internal/cilium/charts/hubble-relay/templates/job.yaml
  charts/internal/cilium/charts/hubble-ui/templates/deployment.yaml
  charts/internal/cilium/charts/nodeinit/templates/daemonset.yaml
  charts/internal/cilium/charts/operator/templates/deployment.yaml
  example/20-network.yaml
  hack/api-reference/cilium.json
  hack/api-reference/config.json
Labels: area/networking, kind/cleanup, needs/ok-to-test, reviewed/lgtm, size/xs

#147 masquerading to the upstream dns server is now configurable
  charts/internal/cilium/charts/agent/templates/daemonset.yaml
  charts/internal/cilium/charts/config/templates/configmap.yaml
  charts/internal/cilium/values.yaml
  docs/usage-as-end-user.md
  hack/api-reference/cilium.md
  pkg/apis/cilium/types_network.go
  pkg/apis/cilium/v1alpha1/types_network.go
  pkg/apis/cilium/v1alpha1/zz_generated.conversion.go
  pkg/apis/cilium/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/cilium/zz_generated.deepcopy.go
  pkg/charts/config.go
  pkg/charts/utils.go
Labels: area/networking, kind/api-change, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/m

#146 Remove image preflight nodeinit.
  charts/images.yaml
  charts/internal/cilium/charts/agent/templates/daemonset.yaml
  charts/internal/cilium/charts/config/templates/configmap.yaml
  charts/internal/cilium/charts/managed-etcd/Chart.yaml
  charts/internal/cilium/charts/managed-etcd/templates/cilium-etcd-operator-clusterrole.yaml
  charts/internal/cilium/charts/managed-etcd/templates/cilium-etcd-operator-clusterrolebinding.yaml
  charts/internal/cilium/charts/managed-etcd/templates/cilium-etcd-operator-deployment.yaml
  charts/internal/cilium/charts/managed-etcd/templates/cilium-etcd-operator-serviceaccount.yaml
  charts/internal/cilium/charts/managed-etcd/templates/etcd-operator-clusterrole.yaml
  charts/internal/cilium/charts/managed-etcd/templates/etcd-operator-clusterrolebinding.yaml
  charts/internal/cilium/charts/managed-etcd/templates/etcd-operator-serviceaccount.yaml
  charts/internal/cilium/charts/nodeinit/Chart.yaml
  charts/internal/cilium/charts/nodeinit/templates/daemonset.yaml
  charts/internal/cilium/charts/nodeinit/values.yaml
  charts/internal/cilium/charts/operator/templates/deployment.yaml
  charts/internal/cilium/charts/preflight/Chart.yaml
  charts/internal/cilium/charts/preflight/templates/clusterrole.yaml
  charts/internal/cilium/charts/preflight/templates/clusterrolebinding.yaml
  charts/internal/cilium/charts/preflight/templates/daemonset.yaml
  charts/internal/cilium/charts/preflight/templates/deployment.yaml
  charts/internal/cilium/charts/preflight/values.yaml
  charts/internal/cilium/requirements.yaml
  charts/internal/cilium/values.yaml
  docs/usage-as-end-user.md
  pkg/apis/cilium/types_network.go
  pkg/apis/cilium/v1alpha1/types_network.go
  pkg/charts/utils.go
  pkg/cilium/types.go
  pkg/imagevector/image_finders.go
Labels: area/networking, kind/api-change, kind/cleanup, needs/ok-to-test, reviewed/lgtm, size/xl

#148 Update to latest golang patch.
  .ci/pipeline_definitions
  Dockerfile
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#149 fix deployment
  charts/gardener-extension-networking-cilium/charts/utils-templates
  charts/gardener-extension-networking-cilium/templates/_helpers.tpl
  example/controller-registration.yaml
Labels: area/networking, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs
