Repository gardener/gardener-extension-networking-cilium, pull requests merged in 2022-06, with the labels that each got.

#94 Update cilium to v1.11.5
  charts/images.yaml
  charts/internal/cilium/charts/agent/templates/clusterrole.yaml
  charts/internal/cilium/charts/config/templates/configmap.yaml
  charts/internal/cilium/charts/hubble-relay/templates/configmap.yaml
  charts/internal/cilium/charts/hubble-relay/templates/deployment.yaml
  charts/internal/cilium/charts/hubble-ui/templates/deployment.yaml
  charts/internal/cilium/charts/hubble-ui/templates/hubble-peer-svc.yaml
  charts/internal/cilium/charts/operator/templates/clusterrole.yaml
  charts/internal/cilium/values.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/m

#95 Consider tunnel mode and debug option in the provider config during reconciliation.
  pkg/charts/utils.go
Labels: area/networking, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#96 Consider tunnel mode and debug option in the provider config during reconciliation.
  VERSION
  example/controller-registration.yaml
  pkg/charts/utils.go
Labels: area/networking, kind/bug, reviewed/ok-to-test, reviewed/lgtm, size/xs

#99 Update cilium to v1.11.6.
  charts/images.yaml
  charts/internal/cilium/charts/agent/templates/daemonset.yaml
  charts/internal/cilium/charts/config/templates/configmap.yaml
  charts/internal/cilium/charts/hubble-ui/templates/configmap.yaml
  charts/internal/cilium/charts/hubble-ui/templates/deployment.yaml
  charts/internal/cilium/charts/hubble-ui/templates/hubble-peer-svc.yaml
  charts/internal/cilium/charts/hubble-ui/templates/svc.yaml
  charts/internal/cilium/values.yaml
  docs/usage-as-end-user.md
  pkg/charts/utils.go
  pkg/cilium/types.go
  pkg/imagevector/image_finders.go
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/m

#101 Support node local dns shoot spec
  go.mod
  go.sum
  pkg/charts/utils.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/reconciler.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/shoot.go
  vendor/github.com/gardener/gardener/extensions/pkg/webhook/certificates/certificates.go
  vendor/github.com/gardener/gardener/hack/test-e2e-local.sh
  vendor/github.com/gardener/gardener/hack/tools.mk
  vendor/github.com/gardener/gardener/pkg/apis/core/types_shoot.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/constants/types_constants.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/generated.pb.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/generated.proto
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/helper/helper.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/helper/shootstate_list.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/types_shoot.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/constants/types_constants.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/generated.pb.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/generated.proto
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/helper/helper.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/types_shoot.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/zz_generated.conversion.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/apis/core/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/controllerutils/patch.go
  vendor/github.com/gardener/gardener/pkg/gardenlet/apis/config/v1alpha1/defaults.go
  vendor/github.com/gardener/gardener/pkg/utils/gardener/exposureclass.go
  vendor/github.com/gardener/gardener/pkg/utils/gardener/shoot.go
  vendor/github.com/gardener/gardener/pkg/utils/miscellaneous.go
  vendor/github.com/gardener/gardener/test/framework/commonframework.go
  vendor/github.com/gardener/gardener/test/framework/gardener_utils.go
  vendor/github.com/gardener/gardener/test/framework/gardenerframework.go
  vendor/github.com/gardener/gardener/test/framework/k8s_utils.go
  vendor/github.com/gardener/gardener/test/framework/shootcreationframework.go
  vendor/github.com/gardener/gardener/test/framework/shootframework.go
  vendor/modules.txt
Labels: needs/ok-to-test
