Repository gardener/gardener-extension-networking-cilium, pull requests merged in 2022-08, with the labels that each got.

#114 Remove install-requirement and use tools.mk
  .gitignore
  Makefile
  hack/tools/bin/.gitkeep
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#115 Add admission controller for cilium to disable kube-proxy unless already specified.
  .ci/pipeline_definitions
  Dockerfile
  Makefile
  charts/gardener-extension-admission-cilium/.helmignore
  charts/gardener-extension-admission-cilium/Chart.yaml
  charts/gardener-extension-admission-cilium/charts/application/Chart.yaml
  charts/gardener-extension-admission-cilium/charts/application/templates/_helpers.tpl
  charts/gardener-extension-admission-cilium/charts/application/templates/mutatingwebhook-mutator.yaml
  charts/gardener-extension-admission-cilium/charts/application/templates/rbac.yaml
  charts/gardener-extension-admission-cilium/charts/application/templates/serviceaccount.yaml
  charts/gardener-extension-admission-cilium/charts/application/values.yaml
  charts/gardener-extension-admission-cilium/charts/runtime/Chart.yaml
  charts/gardener-extension-admission-cilium/charts/runtime/templates/_helpers.tpl
  charts/gardener-extension-admission-cilium/charts/runtime/templates/deplyoment.yaml
  charts/gardener-extension-admission-cilium/charts/runtime/templates/poddisruptionbudget.yaml
  charts/gardener-extension-admission-cilium/charts/runtime/templates/secret-cert.yaml
  charts/gardener-extension-admission-cilium/charts/runtime/templates/secret-kubeconfig.yaml
  charts/gardener-extension-admission-cilium/charts/runtime/templates/service.yaml
  charts/gardener-extension-admission-cilium/charts/runtime/templates/serviceaccount.yaml
  charts/gardener-extension-admission-cilium/charts/runtime/templates/vpa.yaml
  charts/gardener-extension-admission-cilium/charts/runtime/values.yaml
  charts/gardener-extension-admission-cilium/templates/_helpers.tpl
  charts/gardener-extension-admission-cilium/values.yaml
  cmd/gardener-extension-admission-cilium/app/app.go
  cmd/gardener-extension-admission-cilium/main.go
  example/30-mutatingwebhookconfiguration.yaml
  example/admission-cilium-certs/tls.crt
  example/admission-cilium-certs/tls.key
  go.mod
  pkg/admission/cmd/options.go
  pkg/admission/mutator/shoot.go
  pkg/admission/mutator/webhook.go
  vendor/github.com/gardener/gardener/pkg/healthz/default.go
  vendor/github.com/gardener/gardener/pkg/healthz/healthz.go
  vendor/github.com/gardener/gardener/pkg/healthz/informer.go
  vendor/github.com/gardener/gardener/pkg/healthz/periodic.go
  vendor/modules.txt
Labels: area/networking, kind/enhancement, needs/ok-to-test, needs/review, needs/second-opinion, size/xl

#116 Ensure that the kubernetes api server host is always set when running without kube-proxy.
  charts/internal/cilium/charts/operator/templates/deployment.yaml
  pkg/charts/utils.go
Labels: area/networking, kind/bug, needs/ok-to-test, needs/review, size/s

#119 Fix pod security policy for cilium 1.12 so that it works even if allowPrivilegedContainers is set to false.
  charts/internal/cilium/charts/agent/templates/podsecuritypolicy.yaml
Labels: area/networking, kind/bug, needs/ok-to-test, needs/review, size/xs

#121 Fix mutating web hook for node-local-dns to work with non-default ports.
  pkg/webhook/shoot/node_local_dns.go
Labels: area/networking, kind/bug, needs/ok-to-test, needs/review, size/xs

#123 Do not run cilium/cilium-kube-proxy-clean-up in privileged mode
  charts/internal/cilium/charts/agent/templates/daemonset.yaml
Labels: area/security, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#120 Don't deploy `PSP`s when `PodSecurityPolicy` plugin is disabled
  charts/internal/cilium/charts/agent/templates/daemonset.yaml
  charts/internal/cilium/charts/operator/templates/deployment.yaml
  pkg/charts/utils.go
Labels: area/networking, area/open-source, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs, merge/squash
