Repository gardener/gardener-extension-networking-cilium, pull requests merged in 2022-03, with the labels that each got.

#83 Added cilium network policy to allow non-pod entities on remote nodes to access the cluster dns server.
  charts/internal/cilium/charts/network-policy/Chart.yaml
  charts/internal/cilium/charts/network-policy/templates/dns.yaml
Labels: area/networking, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#86 Support configuration for bpfSocketLBHostnsOnly flag
  charts/internal/cilium/charts/config/templates/configmap.yaml
  charts/internal/cilium/values.yaml
  example/20-network.yaml
  hack/api-reference/cilium.md
  pkg/apis/cilium/types_network.go
  pkg/apis/cilium/v1alpha1/types_network.go
  pkg/apis/cilium/v1alpha1/zz_generated.conversion.go
  pkg/apis/cilium/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/cilium/zz_generated.deepcopy.go
  pkg/charts/config.go
  pkg/charts/utils.go
Labels: area/networking, kind/api-change, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/m

#87 Update cilium to v1.11.3
  charts/images.yaml
  charts/internal/cilium/charts/agent/templates/clusterrole.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#89 Add memory requests and limits to cilium agent container.
  charts/internal/cilium/charts/agent/values.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs
