Repository gardener/gardener-extension-networking-cilium, pull requests merged in 2022-01, with the labels that each got.

#77 `make generate` for the year change
  pkg/apis/cilium/v1alpha1/zz_generated.conversion.go
  pkg/apis/cilium/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/cilium/v1alpha1/zz_generated.defaults.go
  pkg/apis/cilium/zz_generated.deepcopy.go
  pkg/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/config/v1alpha1/zz_generated.defaults.go
  pkg/apis/config/zz_generated.deepcopy.go
Labels: area/networking, needs/ok-to-test, needs/review, size/xs

#75 Update cilium to v1.11.0
  charts/images.yaml
  charts/internal/cilium/charts/agent/templates/clusterrole.yaml
  charts/internal/cilium/charts/agent/templates/daemonset.yaml
  charts/internal/cilium/charts/config/templates/configmap.yaml
  charts/internal/cilium/charts/hubble-relay/templates/clusterrole.yaml
  charts/internal/cilium/charts/hubble-relay/templates/cronjob.yaml
  charts/internal/cilium/charts/hubble-relay/templates/deployment.yaml
  charts/internal/cilium/charts/hubble-relay/templates/job.yaml
  charts/internal/cilium/charts/hubble-ui/templates/clusterrolebinding.yaml
  charts/internal/cilium/charts/hubble-ui/templates/configmap.yaml
  charts/internal/cilium/charts/hubble-ui/templates/deployment.yaml
  charts/internal/cilium/charts/hubble-ui/templates/svc.yaml
  charts/internal/cilium/charts/operator/templates/clusterrole.yaml
  charts/internal/cilium/charts/operator/templates/deployment.yaml
  charts/internal/cilium/values.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/l

#78 Update cilium to v1.11.1
  charts/images.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#79 update golang image to golang:1.17.6
  .ci/pipeline_definitions
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#80 generate once a day the new certs for hubble
  charts/internal/cilium/charts/hubble-relay/templates/job.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs
