Repository gardener/gardener-extension-networking-cilium, pull requests merged in 2022-07, with the labels that each got.

#105 Add default memory requests/limits to etcd-operator container.
  charts/internal/cilium/charts/operator/values.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, needs/review, size/xs

#102 Allow enabling egress gateway feature
  charts/internal/cilium/charts/config/templates/configmap.yaml
  charts/internal/cilium/values.yaml
  hack/api-reference/cilium.md
  pkg/apis/cilium/types_network.go
  pkg/apis/cilium/v1alpha1/types_network.go
  pkg/apis/cilium/v1alpha1/zz_generated.conversion.go
  pkg/apis/cilium/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/cilium/zz_generated.deepcopy.go
  pkg/charts/config.go
  pkg/charts/utils.go
Labels: area/networking, kind/api-change, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/m

#106 Extend documentation for bpfSocketLBHostnsOnly and egressGateway flag
  docs/usage-as-end-user.md
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#109 Exclude some linter checks which don't work with golang v1.18
  .golangci.yaml
Labels: area/networking, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#108 fix cannot merge map onto non-map for key 'egressGateway'
  charts/internal/cilium/values.yaml
Labels: area/networking, kind/bug, needs/ok-to-test, size/xs

#110 fix wrong path in configmap.yaml template
  charts/internal/cilium/charts/config/templates/configmap.yaml
Labels: area/networking, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#111 use distroless image for garnder networking cilium extension
  Dockerfile
Labels: area/networking, area/open-source, area/security, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#93 Add MaxAllowed for VPA objects
  charts/gardener-extension-networking-cilium/templates/vpa.yaml
  charts/gardener-extension-networking-cilium/values.yaml
  example/controller-registration.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs, area/auto-scaling

#103 Adapt the deployment priorityClassName according to the gardener documentation
  charts/gardener-extension-networking-cilium/templates/_helpers.tpl
  charts/gardener-extension-networking-cilium/templates/deployment.yaml
  charts/gardener-extension-networking-cilium/templates/priorityclass.yaml
  charts/utils-templates/templates/_versions.tpl
  example/controller-registration.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#112 Update cilium to v1.12.0
  charts/images.yaml
  charts/internal/cilium/charts/agent/templates/clusterrole.yaml
  charts/internal/cilium/charts/agent/templates/daemonset.yaml
  charts/internal/cilium/charts/config/templates/configmap.yaml
  charts/internal/cilium/charts/hubble-relay/templates/clusterrole.yaml
  charts/internal/cilium/charts/hubble-relay/templates/cronjob.yaml
  charts/internal/cilium/charts/hubble-relay/templates/deployment.yaml
  charts/internal/cilium/charts/hubble-relay/templates/job.yaml
  charts/internal/cilium/charts/hubble-relay/templates/service.yaml
  charts/internal/cilium/charts/hubble-ui/templates/deployment.yaml
  charts/internal/cilium/charts/hubble-ui/templates/svc.yaml
  charts/internal/cilium/charts/operator/templates/clusterrole.yaml
  charts/internal/cilium/charts/operator/templates/deployment.yaml
  charts/internal/cilium/values.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xl

#113 fix hubble deployment
  charts/internal/cilium/charts/hubble-relay/templates/deployment.yaml
Labels: area/networking, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs
