Repository gardener/gardener-extension-networking-cilium, pull requests merged in 2022-11, with the labels that each got.

#137 switch default ipam to kubernetes and use bpf masquerading
  charts/internal/cilium/charts/config/templates/configmap.yaml
  charts/internal/cilium/values.yaml
  pkg/charts/config.go
  pkg/charts/utils.go
  pkg/charts/values.go
  pkg/controller/actuator_reconcile.go
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/s

#136 Update API Core version in examples to core.gardener.cloud/v1beta1
  example/20-network.yaml
Labels: area/usability, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#140 update cilium to v1.12.4
  charts/images.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#141 Update portmap copier to v0.2.0
  charts/images.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs
