Repository gardener/gardener-extension-networking-cilium, pull requests merged in 2023-06, with the labels that each got.

#192 Induce component version using ldflags
  Dockerfile
  Makefile
  cmd/gardener-extension-admission-cilium/app/app.go
  cmd/gardener-extension-admission-cilium/main.go
  cmd/gardener-extension-networking-cilium/app/app.go
  cmd/gardener-extension-networking-cilium/main.go
  vendor/k8s.io/component-base/version/verflag/verflag.go
  vendor/modules.txt
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/s

#193 Allow access to webhook server from shoot API servers
  charts/gardener-extension-networking-cilium/templates/service.yaml
  example/controller-registration.yaml
Labels: area/dev-productivity, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#197 increase bpf-policy-map-max to 65536
  charts/internal/cilium/values.yaml
Labels: area/networking, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs
