Repository gardener/gardener-extension-networking-cilium, pull requests merged in 2023-05, with the labels that each got.

#185 Add support for TopologyAwareHints (topology-aware traffic routing)
  charts/internal/cilium/charts/config/templates/configmap.yaml
  charts/internal/cilium/values.yaml
  docs/usage-as-end-user.md
Labels: area/networking, kind/api-change, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#186 Adapt `NetworkPolicy`s
  charts/gardener-extension-admission-cilium/charts/runtime/templates/deplyoment.yaml
  charts/gardener-extension-admission-cilium/charts/runtime/templates/service.yaml
  charts/gardener-extension-networking-cilium/templates/service.yaml
  example/controller-registration.yaml
Labels: area/networking, area/security, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#187 Update to golang 1.20.4
  .ci/pipeline_definitions
  Dockerfile
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs
