Repository gardener/gardener-extension-networking-cilium, pull requests merged in 2023-10, with the labels that each got.

#220 fix egress gateway validation
  charts/internal/cilium/charts/config/templates/configmap.yaml
Labels: area/networking, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#221 add certs with the correct SAN
  example/30-mutatingwebhookconfiguration.yaml
  example/admission-cilium-certs/tls.crt
  example/admission-cilium-certs/tls.key
Labels: area/networking, kind/bug, needs/ok-to-test, reviewed/lgtm, size/m

#222 update cilium to v1.14.3
  imagevector/images.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#223 update cilium docs for egress gateway feature
  docs/usage/usage.md
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#224 fail if egress gateway is enabled without using an overlay
  charts/internal/cilium/charts/config/templates/configmap.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#212 Introduce the use of central manifest
  .docforge/manifest.yaml
Labels: area/documentation, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#225 Fix versioning in charts
  charts/internal/cilium/charts/agent/templates/podsecuritypolicy.yaml
  charts/internal/cilium/charts/agent/templates/servicemonitor.yaml
  charts/internal/cilium/charts/hubble-relay/templates/podsecuritypolicy.yaml
  charts/internal/cilium/charts/operator/templates/podsecuritypolicy.yaml
  charts/internal/cilium/charts/operator/templates/servicemonitor.yaml
Labels: area/networking, kind/bug, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#226 Fix reconciliation of hibernated clusters.
  pkg/controller/actuator_reconcile.go
Labels: area/networking, kind/bug, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs
