Repository gardener/gardener-extension-networking-cilium, pull requests merged in 2023-04, with the labels that each got.

#177 add hostport 4244 to psp
  charts/internal/cilium/charts/agent/templates/podsecuritypolicy.yaml
Labels: area/networking, kind/bug, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#178 enable hostport 4244 independently of prometheus
  charts/internal/cilium/charts/agent/templates/podsecuritypolicy.yaml
Labels: area/networking, kind/bug, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#180 remove portmap copier
  charts/images.yaml
  charts/internal/cilium/charts/agent/templates/daemonset.yaml
  charts/internal/cilium/values.yaml
  pkg/charts/utils.go
  pkg/cilium/types.go
  pkg/imagevector/image_finders.go
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/s

#181 Export artifacts analogous to gardener/gardener in end-to-end tests
  hack/test-e2e-provider-local.sh
Labels: area/networking, kind/test, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#176 Make the `gardener-extension-admission-cilium` Service topology-aware
  charts/gardener-extension-admission-cilium/charts/runtime/templates/service.yaml
  charts/gardener-extension-admission-cilium/values.yaml
Labels: area/high-availability, area/networking, kind/enhancement, reviewed/ok-to-test, reviewed/lgtm, size/xs

#182 Use `gardener@v1.69.1` for e2e tests
  hack/test-e2e-provider-local.sh
Labels: area/networking, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#183 increase memory limit for cilium agent
  charts/internal/cilium/charts/agent/values.yaml
Labels: area/networking, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs
