Repository gardener/gardener-extension-networking-cilium, pull requests merged in 2023-02, with the labels that each got.

#153 Add responsibles for components and cleanup old snapshot versions.
  .ci/pipeline_definitions
Labels: area/networking, kind/enhancement, needs/ok-to-test, needs/review, size/xs

#152 Mark cilium as node-critical component
  charts/internal/cilium/charts/agent/templates/daemonset.yaml
Labels: area/robustness, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#154 Update cilium to v1.13.0
  charts/images.yaml
  charts/internal/cilium/charts/agent/templates/clusterrole.yaml
  charts/internal/cilium/charts/agent/templates/clusterrolebinding.yaml
  charts/internal/cilium/charts/agent/templates/daemonset.yaml
  charts/internal/cilium/charts/agent/templates/role.yaml
  charts/internal/cilium/charts/agent/templates/rolebinding.yaml
  charts/internal/cilium/charts/config/templates/configmap.yaml
  charts/internal/cilium/charts/hubble-relay/templates/clusterrole.yaml
  charts/internal/cilium/charts/hubble-relay/templates/clusterrolebinding.yaml
  charts/internal/cilium/charts/hubble-relay/templates/cronjob.yaml
  charts/internal/cilium/charts/hubble-relay/templates/deployment.yaml
  charts/internal/cilium/charts/hubble-relay/templates/job.yaml
  charts/internal/cilium/charts/hubble-relay/templates/service.yaml
  charts/internal/cilium/charts/hubble-ui/templates/clusterrole.yaml
  charts/internal/cilium/charts/hubble-ui/templates/clusterrolebinding.yaml
  charts/internal/cilium/charts/hubble-ui/templates/deployment.yaml
  charts/internal/cilium/charts/hubble-ui/templates/hubble-peer-svc.yaml
  charts/internal/cilium/charts/hubble-ui/templates/svc.yaml
  charts/internal/cilium/charts/operator/templates/clusterrole.yaml
  charts/internal/cilium/charts/operator/templates/clusterrolebinding.yaml
  charts/internal/cilium/charts/operator/templates/deployment.yaml
  charts/internal/cilium/values.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/m

#157 Clean up RBAC rules for `dnsrecords`
  charts/gardener-extension-networking-cilium/templates/rbac.yaml
  example/controller-registration.yaml
Labels: kind/cleanup, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs
