Repository gardener/gardener-extension-networking-cilium, pull requests merged in 2024-10, with the labels that each got.

#416 remove digest from cilium-envoy image
  imagevector/images.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#420 Introduce `gosec` for Static Application Security Testing (SAST)
  .gitignore
  Makefile
  hack/sast.sh
  pkg/apis/config/loader/loader.go
Labels: area/networking, area/security, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/s, area/compliance

#421 support ipv6 shoot cluster with cilium
  charts/internal/cilium/charts/agent/templates/daemonset.yaml
  charts/internal/cilium/charts/config/templates/configmap.yaml
  charts/internal/cilium/charts/envoy/templates/configmap.yaml
  charts/internal/cilium/charts/envoy/templates/daemonset.yaml
  charts/internal/cilium/charts/operator/templates/deployment.yaml
  hack/api-reference/cilium.md
  pkg/apis/cilium/types_network.go
  pkg/apis/cilium/v1alpha1/types_network.go
  pkg/apis/cilium/v1alpha1/zz_generated.conversion.go
  pkg/apis/cilium/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/cilium/zz_generated.deepcopy.go
  pkg/charts/config.go
  pkg/charts/utils.go
  pkg/controller/actuator_reconcile.go
Labels: area/networking, kind/api-change, kind/enhancement, needs/ok-to-test, needs/second-opinion, size/m

#422 Add SAST logs to OCM component descriptor
  .ci/pipeline_definitions
Labels: area/networking, area/security, kind/enhancement, needs/ok-to-test, needs/review, size/xs, area/compliance
