Repository gardener/gardener-extension-networking-cilium, pull requests merged in 2024-02, with the labels that each got.

#239 Update cilium to v1.14.6
  Makefile
  charts/internal/cilium/charts/config/templates/configmap.yaml
  imagevector/images.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#241 Add `apiVersion: v1` to gardener-extension-admission-cilium `ServiceAccount`
  charts/gardener-extension-admission-cilium/charts/runtime/templates/serviceaccount.yaml
Labels: area/networking, kind/bug, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#243 set LEADER_ELECTION_NAMESPACE in deployment
  charts/gardener-extension-admission-cilium/charts/runtime/templates/deplyoment.yaml
Labels: area/networking, kind/bug, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#245 Adapt PDBs to use `unhealthyPodEvictionPolicy: AlwaysAllow`
  charts/gardener-extension-admission-cilium/charts/runtime/templates/poddisruptionbudget.yaml
  charts/gardener-extension-admission-cilium/charts/runtime/templates/service.yaml
  charts/gardener-extension-networking-cilium/templates/poddisruptionbudget.yaml
  charts/gardener-extension-networking-cilium/templates/service.yaml
  charts/internal/cilium/charts/operator/templates/poddisruptionbudget.yaml
  example/controller-registration.yaml
  hack/test-e2e-provider-local.sh
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs
