Repository gardener/gardener-extension-networking-cilium, pull requests merged in 2024-09, with the labels that each got.

#409 update cilium to v1.16.1
  charts/internal/cilium/charts/agent/templates/clusterrole.yaml
  charts/internal/cilium/charts/agent/templates/daemonset.yaml
  charts/internal/cilium/charts/config/templates/configmap.yaml
  charts/internal/cilium/charts/envoy/Chart.yaml
  charts/internal/cilium/charts/envoy/templates/configmap.yaml
  charts/internal/cilium/charts/envoy/templates/daemonset.yaml
  charts/internal/cilium/charts/envoy/templates/serviceaccount.yaml
  charts/internal/cilium/charts/envoy/values.yaml
  charts/internal/cilium/charts/hubble-relay/templates/cronjob.yaml
  charts/internal/cilium/charts/hubble-relay/templates/deployment.yaml
  charts/internal/cilium/charts/hubble-relay/templates/job.yaml
  charts/internal/cilium/charts/hubble-relay/templates/role.yaml
  charts/internal/cilium/charts/hubble-relay/templates/rolebinding.yaml
  charts/internal/cilium/charts/hubble-ui/templates/deployment.yaml
  charts/internal/cilium/charts/operator/templates/clusterrole.yaml
  charts/internal/cilium/charts/operator/templates/deployment.yaml
  charts/internal/cilium/values.yaml
  imagevector/image_finders.go
  imagevector/images.yaml
  pkg/charts/utils.go
  pkg/cilium/types.go
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xl

#408 Remove VPA `(min|max)Allowed` settings.
  charts/gardener-extension-admission-cilium/values.yaml
  charts/gardener-extension-networking-cilium/values.yaml
  example/controller-registration.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs, area/auto-scaling

#411 update to cilium v1.16.2
  charts/internal/cilium/charts/envoy/templates/daemonset.yaml
  charts/internal/cilium/charts/envoy/templates/service.yaml
  imagevector/images.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/s
