Repository gardener/gardener-extension-networking-cilium, pull requests merged in 2024-04, with the labels that each got.

#284 run e2e test cluster without kube-proxy
  test/e2e/common_test.go
Labels: area/networking, kind/enhancement, needs/ok-to-test, needs/review, size/xs

#282 update cilium to v1.15.3
  charts/internal/cilium/charts/agent/templates/clusterrole.yaml
  charts/internal/cilium/charts/agent/templates/daemonset.yaml
  charts/internal/cilium/charts/config/templates/configmap.yaml
  charts/internal/cilium/charts/hubble-relay/templates/deployment.yaml
  charts/internal/cilium/charts/hubble-ui/templates/configmap.yaml
  charts/internal/cilium/charts/hubble-ui/templates/deployment.yaml
  charts/internal/cilium/charts/operator/templates/clusterrole.yaml
  imagevector/images.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/s

#287 Add scanning hint for envoy
  imagevector/images.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs
