Repository gardener/gardener-extension-networking-cilium, pull requests merged in 2025-02, with the labels that each got.

#494 test(e2e): access kube-apiserver through apiserver-proxy
  test/templates/network-test.yaml.tpl
Labels: area/networking, kind/test, needs/ok-to-test, needs/review, size/xs, needs-ok-to-test

#487 Forbid container privilege escalations.
  charts/gardener-extension-admission-cilium/charts/runtime/templates/deplyoment.yaml
  charts/gardener-extension-networking-cilium/templates/deployment.yaml
  charts/internal/cilium/charts/agent/templates/daemonset.yaml
  charts/internal/cilium/charts/hubble-relay/templates/deployment.yaml
  charts/internal/cilium/charts/hubble-ui/templates/deployment.yaml
  charts/internal/cilium/charts/operator/templates/deployment.yaml
  example/controller-registration.yaml
Labels: area/security, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs, area/compliance

#350 fix: enable-bpf-masquerade when snat values are not enabled
  charts/internal/cilium/charts/config/templates/configmap.yaml
Labels: area/networking, needs/ok-to-test, needs/rebase, reviewed/lgtm, size/xs, ok-to-test

#492 disable health-check when not replacing kubeproxy
  charts/internal/cilium/charts/config/templates/configmap.yaml
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, needs-ok-to-test, ok-to-test

#496 Revert "test: access kube-apiserver through apiserver-proxy"
  test/templates/network-test.yaml.tpl
Labels: area/networking, kind/test, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs, status/accepted

#483 Prepare for deployment of admission controller by gardener-operator
  .ci/pipeline_definitions
  charts/gardener-extension-admission-cilium/Chart.yaml
  charts/gardener-extension-admission-cilium/charts/application/.helmignore
  charts/gardener-extension-admission-cilium/charts/application/templates/_helpers.tpl
  charts/gardener-extension-admission-cilium/charts/application/templates/rbac.yaml
  charts/gardener-extension-admission-cilium/charts/application/templates/serviceaccount.yaml
  charts/gardener-extension-admission-cilium/charts/application/values.yaml
  charts/gardener-extension-admission-cilium/charts/runtime/.helmignore
  charts/gardener-extension-admission-cilium/charts/runtime/templates/deployment.yaml
  charts/gardener-extension-admission-cilium/charts/runtime/templates/secret-kubeconfig.yaml
  charts/gardener-extension-admission-cilium/charts/runtime/templates/service.yaml
  charts/gardener-extension-admission-cilium/charts/runtime/templates/vpa.yaml
  charts/gardener-extension-admission-cilium/charts/runtime/values.yaml
  charts/gardener-extension-admission-cilium/templates/_helpers.tpl
  charts/gardener-extension-admission-cilium/values.yaml
  cmd/gardener-extension-admission-cilium/app/app.go
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/m

#506 Make extension ports configurable via helm values
  charts/gardener-extension-networking-cilium/templates/deployment.yaml
  charts/gardener-extension-networking-cilium/templates/service.yaml
  charts/gardener-extension-networking-cilium/values.yaml
  example/controller-registration.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#501 Re-enable "test: access kube-apiserver through apiserver-proxy"
  test/templates/network-test.yaml.tpl
Labels: area/networking, kind/test, needs/ok-to-test, needs/review, size/xs

#510 Update cilium to v1.17.1
  charts/internal/cilium/charts/config/templates/configmap.yaml
  charts/internal/cilium/charts/envoy/templates/configmap.yaml
  charts/internal/cilium/charts/envoy/templates/daemonset.yaml
  charts/internal/cilium/charts/hubble-relay/templates/configmap.yaml
  charts/internal/cilium/charts/hubble-relay/templates/cronjob.yaml
  charts/internal/cilium/charts/hubble-relay/templates/job.yaml
  charts/internal/cilium/charts/operator/templates/clusterrole.yaml
  charts/internal/cilium/charts/operator/templates/deployment.yaml
  charts/internal/cilium/values.yaml
  imagevector/images.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, needs/review, size/m

#512 Update pipeline_definitions
  .ci/pipeline_definitions
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs
