Repository gardener/gardener-extension-networking-cilium, pull requests merged in 2025-07, with the labels that each got.

#587 fix: disable vpa to stabilize con tests
  test/e2e/common_test.go
Labels: area/networking, size/S, kind/flake, cla: yes, approved, lgtm, reviewed/ok-to-test

#596 Update module github.com/gardener/gardener to v1.123.1
  .ci/hack/component_descriptor
  .ci/hack/doc.go
  .ci/hack/prepare_release
  .ci/hack/set_dependency_version
  go.mod
  go.sum
  hack/sast.sh
  renovate.json5
Labels: area/networking, kind/enhancement, size/XL, cla: yes, approved, lgtm

#597 Drop support for Shoots with Kubernetes version <= 1.28
  example/20-network.yaml
  hack/api-reference/config.json
Labels: area/networking, kind/cleanup, size/XS, cla: yes, approved, lgtm, reviewed/ok-to-test

#602 Fix 'add-reports-to-component-descriptor' build step
  .github/workflows/build.yaml
Labels: area/networking, kind/task, size/XS, area/compliance, cla: yes, approved, lgtm, reviewed/ok-to-test
