Repository gardener/gardener-extension-networking-cilium, pull requests merged in 2025-08, with the labels that each got.

#603 Configure `kube-proxy-replacement-healthz-bind-address` in case `kube-proxy` is disabled.
  pkg/charts/config.go
  pkg/charts/utils.go
Labels: area/networking, kind/enhancement, size/M, cla: yes, approved, lgtm

#605 allow hubble-generate-certs job access to api (via internal domain)
  charts/internal/cilium/charts/hubble-relay/templates/cronjob.yaml
  charts/internal/cilium/charts/hubble-relay/templates/job.yaml
Labels: area/networking, kind/bug, size/XS, ok-to-test, cla: yes, approved, lgtm

#606 fix: include apiserver label for private clouds
  charts/internal/cilium/charts/hubble-relay/templates/cronjob.yaml
  charts/internal/cilium/charts/hubble-relay/templates/job.yaml
Labels: area/networking, kind/bug, size/XS, cla: yes, approved, lgtm

#608 Fix a bug that prevented prometheus from storing cilium metrics.
  charts/internal/cilium-monitoring/templates/scrapeconfig-agent.yaml
  charts/internal/cilium-monitoring/templates/scrapeconfig-hubble.yaml
  charts/internal/cilium-monitoring/templates/scrapeconfig-operator.yaml
Labels: area/monitoring, kind/bug, size/S, cla: yes, approved, lgtm, reviewed/ok-to-test

#609 Fix Dual-Stack handling of native IPv6 routing CIDR.
  pkg/charts/utils.go
Labels: area/networking, kind/bug, size/S, cla: yes, approved, lgtm

#611 Fix migration to dual-stack
  pkg/controller/status.go
Labels: area/networking, kind/bug, size/XS, cla: yes, approved, lgtm

#623 Add generation for `Extension` example
  Makefile
  example/doc.go
  example/extension.yaml
  example/extension/base/extension.yaml
  example/extension/base/kustomization.yaml
  example/extension/extension.yaml
  example/extension/kustomization.yaml
Labels: kind/enhancement, size/M, area/ipcei, cla: yes, approved, lgtm

#626 Hotfix: Update cilium images to v1.17.7 (patch)
  charts/internal/cilium/charts/agent/templates/daemonset.yaml
  imagevector/images.yaml
Labels: area/networking, kind/enhancement, size/S, cla: yes, approved, lgtm, reviewed/ok-to-test
