Repository gardener/gardener-extension-networking-cilium, pull requests merged in 2025-06, with the labels that each got.

#573 feat: allow disabling BPF masquerading
  charts/internal/cilium/charts/config/templates/configmap.yaml
  hack/api-reference/cilium.md
  pkg/apis/cilium/types_network.go
  pkg/apis/cilium/v1alpha1/types_network.go
  pkg/apis/cilium/v1alpha1/zz_generated.conversion.go
  pkg/apis/cilium/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/cilium/zz_generated.deepcopy.go
  pkg/charts/config.go
  pkg/charts/utils.go
  renovate.json5
Labels: area/networking, size/L, ok-to-test, cla: yes, approved, lgtm

#582 Remove `gardener/gardener-maintainers` from `CODEOWNERS` file
  CODEOWNERS
Labels: area/networking, kind/cleanup, size/XS, cla: yes, approved, lgtm

#584 Improve Input Validation of Provider-Specific Configuration
  go.mod
  go.sum
  hack/api-reference/cilium.md
  pkg/admission/cmd/options.go
  pkg/admission/mutator/webhook.go
  pkg/admission/validator/shoot.go
  pkg/admission/validator/webhook.go
  pkg/apis/cilium/types_network.go
  pkg/apis/cilium/v1alpha1/types_network.go
  pkg/apis/cilium/validation/networkconfig.go
  pkg/apis/cilium/validation/networkconfig_test.go
  pkg/apis/cilium/validation/shoot.go
  pkg/apis/cilium/validation/shoot_test.go
  pkg/apis/cilium/validation/validation_suite_test.go
  pkg/apis/cilium/zz_generated.deepcopy.go
  pkg/controller/actuator_reconcile.go
  pkg/controller/validate.go
  renovate.json5
Labels: area/networking, area/robustness, kind/enhancement, size/XL, cla: yes, approved, lgtm, reviewed/ok-to-test
